Feat/edit comment
TheWidlarzGroup/holidaily pull request #687
Opened 2022-06-07 14:52 UTC by lukbar48

2022-06-09 08:46 UTC, iceu-bb requested changes

2022-06-09 08:46 UTC, iceu-bb commented on src/data-access/mutations/useAddReactionsComment.ts
> +}
I think you can only pass `commentId` as an argument here, don't need to pass the whole comment 🤔

2022-06-09 08:46 UTC, iceu-bb commented on src/data-access/mutations/useAddReactionsComment.ts
> +        return allPosts
Is there a need to return `allPosts` from the delete hook?

2022-06-09 08:46 UTC, iceu-bb commented on src/screens/feed/Feed.tsx
> +    if (!(target.author === `${user?.firstName} ${user?.lastName}`)) return
- Can we check the author by `id`? If the user will change the name this logic will be broken

2022-06-09 08:46 UTC, iceu-bb commented on src/screens/feed/Feed.tsx
> +  const handleModalDelete = () => {
```suggestion
  const onCommentDelete = () => {
```

2022-06-09 08:46 UTC, iceu-bb commented on src/screens/feed/components/CommentBox/CommentBox.tsx
> +            id={comments[comments.length - 1].id}
`comments[comments.length - 1]` can be declared as variable

2022-06-09 08:53 UTC, lukbar48 commented on src/data-access/mutations/useAddReactionsComment.ts
> +}
there is passed commentId and postID as object in data

2022-06-10 07:31 UTC, iceu-bb requested changes

2022-06-10 07:31 UTC, iceu-bb commented on src/screens/feed/Feed.tsx
> +    useBooleanState(false)
I think you may not need `isEditingComment` state as you can check

`if(editTarget.type === "comment")`

2022-06-10 07:31 UTC, iceu-bb commented on src/screens/feed/Feed.tsx
> +  const [isModalOpen, { setFalse: closeModal, setTrue: openModal }] = useBooleanState(false)
```suggestion
  const [isOptionsModalOpen, { setFalse: closeOptionsModal, setTrue: openOptionsModal }] = useBooleanState(false)
```

2022-06-10 07:31 UTC, iceu-bb commented on src/screens/feed/Feed.tsx
> +  const [messageContent, setMessageContent] = useState('')
I wonder if you can derive `messageContent` from `editTarget.text` and use it as a source of truth ?

2022-06-10 07:31 UTC, iceu-bb commented on src/screens/feed/Feed.tsx
> +      })
```suggestion
      editComment({ ...editTarget, text: messageContent })
```

2022-06-14 07:11 UTC, iceu-bb approved these changes

2022-06-14 08:11 UTC, merged